"""add revoked_at field to sessions table

Revision ID: f575fd283fb9
Revises: 173f728d9294
Create Date: 2025-08-15 19:25:16.739727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f575fd283fb9'
down_revision: Union[str, Sequence[str], None] = '173f728d9294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'revoked_at')
    # ### end Alembic commands ###
